export const ADDON_PLANS = {
  digitalContent: [
    { label: "구글 원(Google One)", value: "google_one" },
    { label: "유튜브 프리미엄", value: "youtube_premium" },
    { label: "티빙 프리미엄", value: "tving_premium" },
    { label: "티빙 스탠다드", value: "tving_standard" },
    { label: "티빙 베이직", value: "tving_basic" },
    { label: "디즈니+ 프리미엄", value: "disney_plus_premium" },
    { label: "디즈니+ 스탠다드", value: "disney_plus_standard" },
    { label: "넷플릭스 프리미엄", value: "netflix_premium" },
    { label: "넷플릭스 스탠다드", value: "netflix_standard" },
    { label: "모두의할인팩", value: "everyone_discount_pack" },
    { label: "아이들나라 프리미엄", value: "kids_nara_premium" },
    { label: "아이들나라 스탠다드", value: "kids_nara_standard" },
    { label: "아이들나라 플레이", value: "kids_nara_play" },
    { label: "지니뮤직", value: "genie_music" },
    { label: "지니뮤직 마음껏 듣기(모바일전용)", value: "genie_music_unlimited_mobile" },
    { label: "지니뮤직 마음껏 듣기(모든 디바이스)", value: "genie_music_unlimited_all_devices" },
    { label: "V컬러링 음악감상 플러스", value: "v_coloring_music_plus" },
    { label: "g 포인트 혜택 업그레이드 A", value: "g_point_upgrade_a" },
    { label: "g 포인트 혜택 업그레이드 B", value: "g_point_upgrade_b" },
    { label: "U+모바일tv", value: "uplus_mobile_tv" },
  ] as const,

  familyCare: [
    { label: "딥페이크안심보호", value: "deepfake_safe_protection" },
    { label: "자녀안전지킴이", value: "child_safety_guard" },
    { label: "스팸차단후후", value: "spam_block_whowho" },
    { label: "가족안부전화", value: "family_check_call" },
    { label: "휴대폰가족보호", value: "phone_family_protection" },
    { label: "자녀폰지킴이", value: "child_phone_guard" },
    { label: "스마트안티피싱", value: "smart_anti_phishing" },
    { label: "휴대폰번호 보호서비스", value: "phone_number_protection_service" },
    { label: "스마트피싱보호", value: "smart_phishing_protection" },
    { label: "오토콜", value: "auto_call" },
    { label: "원키퍼", value: "one_keeper" },
    { label: "금융사고안심팩", value: "financial_accident_safe_pack" },
    { label: "로그인플러스", value: "login_plus" },
    { label: "전화번호안심로그인", value: "phone_number_safe_login" },
    { label: "간편결제매니", value: "easy_payment_mani" },
    { label: "모션키", value: "motion_key" },
    { label: "유비키인증서", value: "ubikey_certificate" },
    { label: "모바일안전결제(ISP)", value: "mobile_safe_payment_isp" },
    { label: "USIM 스마트인증(라온시큐어)", value: "usim_smart_auth_raonsecure" },
    { label: "스마트공동인증(드림시큐리티)", value: "smart_joint_auth_dreamsecurity" },
    { label: "스마트 안전결제", value: "smart_safe_payment" },
    { label: "MyOTP", value: "my_otp" },
  ] as const,

  phoneCare: [
    { label: "폰교체 패스 (휴대폰보험)", value: "phone_replace_pass_insurance" },
    { label: "폰 안심패스 (휴대폰보험)", value: "phone_safe_pass_insurance" },
    { label: "폰교체 슬림 (구.맘대로 폰교체 / 맘대로 폰교체 플러스)", value: "phone_replace_slim" },
  ] as const,
} as const;
