export const ADDON_PLANS = {
  digitalContent: [
    { label: "구글 원(Google One)", value: "ADDON_DIG_001" },
    { label: "유튜브 프리미엄", value: "ADDON_DIG_002" },
    { label: "티빙 프리미엄", value: "ADDON_DIG_003" },
    { label: "티빙 스탠다드", value: "ADDON_DIG_004" },
    { label: "티빙 베이직", value: "ADDON_DIG_005" },
    { label: "디즈니+ 프리미엄", value: "ADDON_DIG_006" },
    { label: "디즈니+ 스탠다드", value: "ADDON_DIG_007" },
    { label: "넷플릭스 프리미엄", value: "ADDON_DIG_008" },
    { label: "넷플릭스 스탠다드", value: "ADDON_DIG_009" },
    { label: "모두의할인팩", value: "ADDON_DIG_010" },
    { label: "아이들나라 프리미엄", value: "ADDON_DIG_011" },
    { label: "아이들나라 스탠다드", value: "ADDON_DIG_012" },
    { label: "아이들나라 플레이", value: "ADDON_DIG_013" },
    { label: "지니뮤직", value: "ADDON_DIG_014" },
    { label: "지니뮤직 마음껏 듣기(모바일전용)", value: "ADDON_DIG_015" },
    { label: "지니뮤직 마음껏 듣기(모든 디바이스)", value: "ADDON_DIG_016" },
    { label: "V컬러링 음악감상 플러스", value: "ADDON_DIG_017" },
    { label: "g 포인트 혜택 업그레이드 A", value: "ADDON_DIG_018" },
    { label: "g 포인트 혜택 업그레이드 B", value: "ADDON_DIG_019" },
    { label: "U+모바일tv", value: "ADDON_DIG_020" },
    { label: "뮤직벨링(통화연결음,벨소리,MP3,지니뮤직 음악감상)", value: "ADDON_DIG_021" },
  ] as const,

  familyCare: [
    { label: "딥페이크안심보호", value: "ADDON_FAM_001" },
    { label: "자녀안전지킴이", value: "ADDON_FAM_002" },
    { label: "스팸차단후후", value: "ADDON_FAM_003" },
    { label: "가족안부전화", value: "ADDON_FAM_004" },
    { label: "휴대폰가족보호", value: "ADDON_FAM_005" },
    { label: "자녀폰지킴이", value: "ADDON_FAM_006" },
    { label: "스마트안티피싱", value: "ADDON_FAM_007" },
    { label: "휴대폰번호 보호서비스", value: "ADDON_FAM_008" },
    { label: "스마트피싱보호", value: "ADDON_FAM_009" },
    { label: "오토콜", value: "ADDON_FAM_010" },
    { label: "원키퍼", value: "ADDON_FAM_011" },
    { label: "금융사고안심팩", value: "ADDON_FAM_012" },
    { label: "로그인플러스", value: "ADDON_FAM_013" },
    { label: "전화번호안심로그인", value: "ADDON_FAM_014" },
    { label: "간편결제매니", value: "ADDON_FAM_015" },
    { label: "모션키", value: "ADDON_FAM_016" },
    { label: "유비키인증서", value: "ADDON_FAM_017" },
    { label: "모바일안전결제(ISP)", value: "ADDON_FAM_018" },
    { label: "USIM 스마트인증(라온시큐어)", value: "ADDON_FAM_019" },
    { label: "스마트공동인증(드림시큐리티)", value: "ADDON_FAM_020" },
    { label: "스마트 안전결제", value: "ADDON_FAM_021" },
    { label: "MyOTP", value: "ADDON_FAM_022" },
  ] as const,

  phoneCare: [
    { label: "폰교체 패스 (휴대폰보험)", value: "ADDON_PH_001" },
    { label: "폰 안심패스 (휴대폰보험)", value: "ADDON_PH_002" },
    { label: "폰교체 슬림 (구.맘대로 폰교체 / 맘대로 폰교체 플러스)", value: "ADDON_PH_003" },
  ] as const,
} as const;
