import type { MultiSelectOption } from "../customerFilters";

export const MOBILE_PLANS = {
  fiveG: [
    { label: "5G 프리미어 에센셜", value: "5g_premier_essential" },
    { label: "5G 스탠다드", value: "5g_standard" },
    { label: "5G 프리미어 레귤러", value: "5g_premier_regular" },
    { label: "유쓰 5G 스탠다드", value: "youth_5g_standard" },
    { label: "5G 데이터 레귤러", value: "5g_data_regular" },
    { label: "5G 데이터 플러스", value: "5g_data_plus" },
    { label: "5G 심플+", value: "5g_simple_plus" },
    { label: "유쓰 5G 데이터 플러스", value: "youth_5g_data_plus" },
    { label: "5G 라이트+", value: "5g_light_plus" },
    { label: "유쓰 5G 라이트+", value: "youth_5g_light_plus" },
    { label: "5G 미니", value: "5g_mini" },
    { label: "5G 슬림+", value: "5g_slim_plus" },
    { label: "5G 프리미어 플러스", value: "5g_premier_plus" },
    { label: "5G 프리미어 슈퍼", value: "5g_premier_super" },
    { label: "5G 시니어 B형", value: "5g_senior_b" },
    { label: "유쓰 5G 슬림+", value: "youth_5g_slim_plus" },
    { label: "유쓰 5G 데이터 레귤러", value: "youth_5g_data_regular" },
    { label: "5G 베이직+", value: "5g_basic_plus" },
    { label: "5G 시니어 A형", value: "5g_senior_a" },
    { label: "유쓰 5G 미니", value: "youth_5g_mini" },
    { label: "유쓰 5G 베이직+", value: "youth_5g_basic_plus" },
    { label: "5G 스탠다드 에센셜", value: "5g_standard_essential" },
    { label: "유쓰 5G 심플+", value: "youth_5g_simple_plus" },
    { label: "5G 시니어 C형", value: "5g_senior_c" },
    { label: "5G 데이터 슈퍼", value: "5g_data_super" },
    { label: "유쓰 5G 스탠다드 에센셜", value: "youth_5g_standard_essential" },
    { label: "5G 시그니처", value: "5g_signature" },
    { label: "유쓰 5G 데이터 슈퍼", value: "youth_5g_data_super" },
    { label: "5G 라이트 청소년", value: "5g_light_youth" },
    { label: "5G 복지 55", value: "5g_welfare_55" },
    { label: "5G 복지 75", value: "5g_welfare_75" },
    { label: "5G 키즈 29", value: "5g_kids_29" },
    { label: "5G 키즈 39", value: "5g_kids_39" },
    { label: "5G 키즈 45", value: "5g_kids_45" },
  ] as const satisfies readonly MultiSelectOption[],

  lte: [
    { label: "데이터 시니어 33", value: "lte_data_senior_33" },
    { label: "데이터 33", value: "lte_data_33" },
    { label: "LTE 표준", value: "lte_standard" },
    { label: "시니어16.5", value: "senior_16_5" },
    { label: "추가 요금 걱정 없는 데이터 69", value: "lte_no_worry_data_69" },
    { label: "현역병사 데이터 55", value: "lte_soldier_data_55" },
    { label: "현역병사 데이터 33", value: "lte_soldier_data_33" },
    { label: "추가 요금 걱정 없는 데이터 시니어 69", value: "lte_no_worry_data_senior_69" },
    { label: "추가 요금 걱정 없는 데이터 청소년 33", value: "lte_no_worry_data_youth_33" },
    { label: "추가 요금 걱정 없는 데이터 청소년 69", value: "lte_no_worry_data_youth_69" },
    { label: "복지 33", value: "lte_welfare_33" },
    { label: "LTE청소년19", value: "lte_youth_19" },
    { label: "복지 49", value: "lte_welfare_49" },
    { label: "LTE 선택형 요금제", value: "lte_select" },
    { label: "LTE 키즈 22(만 12세 이하)", value: "lte_kids_22_under_12" },
    { label: "추가 요금 걱정 없는 데이터 청소년 59", value: "lte_no_worry_data_youth_59" },
  ] as const satisfies readonly MultiSelectOption[],
} as const;
