import type { MultiSelectOption } from "../customerFilters";

export const MOBILE_PLANS = {
  fiveG: [
    { label: "5G 프리미어 에센셜", value: "PLAN_MOB_001" },
    { label: "5G 스탠다드", value: "PLAN_MOB_002" },
    { label: "5G 프리미어 레귤러", value: "PLAN_MOB_003" },
    { label: "유쓰 5G 스탠다드", value: "PLAN_MOB_004" },
    { label: "5G 데이터 레귤러", value: "PLAN_MOB_005" },
    { label: "5G 데이터 플러스", value: "PLAN_MOB_006" },
    { label: "5G 심플+", value: "PLAN_MOB_007" },
    { label: "유쓰 5G 데이터 플러스", value: "PLAN_MOB_008" },
    { label: "5G 라이트+", value: "PLAN_MOB_009" },
    { label: "유쓰 5G 라이트+", value: "PLAN_MOB_010" },
    { label: "5G 미니", value: "PLAN_MOB_011" },
    { label: "5G 슬림+", value: "PLAN_MOB_012" },
    { label: "5G 프리미어 플러스", value: "PLAN_MOB_013" },
    { label: "5G 프리미어 슈퍼", value: "PLAN_MOB_014" },
    { label: "5G 시니어 B형", value: "PLAN_MOB_015" },
    { label: "유쓰 5G 슬림+", value: "PLAN_MOB_016" },
    { label: "유쓰 5G 데이터 레귤러", value: "PLAN_MOB_018" },
    { label: "5G 베이직+", value: "PLAN_MOB_019" },
    { label: "5G 시니어 A형", value: "PLAN_MOB_020" },
    { label: "유쓰 5G 미니", value: "PLAN_MOB_021" },
    { label: "유쓰 5G 베이직+", value: "PLAN_MOB_022" },
    { label: "5G 스탠다드 에센셜", value: "PLAN_MOB_023" },
    { label: "유쓰 5G 심플+", value: "PLAN_MOB_025" },
    { label: "5G 시니어 C형", value: "PLAN_MOB_026" },
    { label: "5G 데이터 슈퍼", value: "PLAN_MOB_027" },
    { label: "유쓰 5G 스탠다드 에센셜", value: "PLAN_MOB_029" },
    { label: "5G 시그니처", value: "PLAN_MOB_030" },
    { label: "유쓰 5G 데이터 슈퍼", value: "PLAN_MOB_032" },
    { label: "5G 라이트 청소년", value: "PLAN_MOB_036" },
    { label: "5G 복지 55", value: "PLAN_MOB_041" },
    { label: "5G 복지 75", value: "PLAN_MOB_043" },
    { label: "5G 키즈 29", value: "PLAN_MOB_045" },
    { label: "5G 키즈 39", value: "PLAN_MOB_046" },
    { label: "5G 키즈 45", value: "PLAN_MOB_047" },
  ] as const satisfies readonly MultiSelectOption[],

  lte: [
    { label: "(LTE) 데이터 시니어 33", value: "PLAN_MOB_017" },
    { label: "(LTE) 데이터 33", value: "PLAN_MOB_024" },
    { label: "시니어16.5", value: "PLAN_MOB_031" },
    { label: "(LTE) 추가 요금 걱정 없는 데이터 69", value: "PLAN_MOB_033" },
    { label: "(LTE) 현역병사 데이터 55", value: "PLAN_MOB_034" },
    { label: "(LTE) 현역병사 데이터 33", value: "PLAN_MOB_035" },
    { label: "(LTE) 추가 요금 걱정 없는 데이터 시니어 69", value: "PLAN_MOB_037" },
    { label: "(LTE) 추가 요금 걱정 없는 데이터 청소년 33", value: "PLAN_MOB_038" },
    { label: "(LTE) 추가 요금 걱정 없는 데이터 청소년 69", value: "PLAN_MOB_039" },
    { label: "(LTE) 복지 33", value: "PLAN_MOB_040" },
    { label: "LTE청소년19", value: "PLAN_MOB_042" },
    { label: "(LTE) 복지 49", value: "PLAN_MOB_044" },
    { label: "LTE 선택형 요금제", value: "PLAN_MOB_048" },
    { label: "LTE 키즈 22(만 12세 이하)", value: "PLAN_MOB_049" },
    { label: "(LTE) 추가 요금 걱정 없는 데이터 청소년 59", value: "PLAN_MOB_050" },
  ] as const satisfies readonly MultiSelectOption[],
} as const;
